apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.config.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: demo
spec:
  ports:
  - name: "6868"
    port: 6868
    targetPort: 8080
  selector:
    io.kompose.service: app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.config.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
  namespace: demo
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mysqldb
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.config.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: mysqldb
        - name: DB_NAME
          value: bezkoder_db
        - name: DB_PASSWORD
          value: "123456"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: MYSQLDB_DATABASE
          value: bezkoder_db
        - name: MYSQLDB_DOCKER_PORT
          value: "3306"
        - name: MYSQLDB_LOCAL_PORT
          value: "3307"
        - name: MYSQLDB_ROOT_PASSWORD
          value: "123456"
        - name: MYSQLDB_USER
          value: root
        - name: NODE_DOCKER_PORT
          value: "8080"
        - name: NODE_LOCAL_PORT
          value: "6868"
        image: alsonchang/nodejsapp:e6fea6
        name: app
        ports:
        - containerPort: 8080
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.config.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
      - env:
        - name: MYSQLDB_DATABASE
          value: bezkoder_db
        - name: MYSQLDB_DOCKER_PORT
          value: "3306"
        - name: MYSQLDB_LOCAL_PORT
          value: "3307"
        - name: MYSQLDB_ROOT_PASSWORD
          value: "123456"
        - name: MYSQLDB_USER
          value: root
        - name: MYSQL_DATABASE
          value: bezkoder_db
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: NODE_DOCKER_PORT
          value: "8080"
        - name: NODE_LOCAL_PORT
          value: "6868"
        image: mysql:5.7
        name: mysqldb
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
